version: "3.5"
services:
  # turborepo
  turbo:
    container_name: turborepo-starter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "8787:8787"
    volumes:
      - ./:/app/
        # Just specify a path and let the Engine create a volume
      - /app/node_modules/
    restart: on-failure
    tty: true
  db:
    image: postgres:9.6
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5