name = "backend"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]



[vars]
MJ_APIKEY_PUBLIC="27efa8d73c7d46ea39fa371220276269"
MJ_APIKEY_PRIVATE="98d42ec38856564b1b2263f0ac741ca9"

UPSTASH_REDIS_REST_TOKEN = "AbUuAAIjcDExZjU0NmEwYWMwYTk0OWM3YmJiOTU0YzU2NTZkMDdkZnAxMA"
UPSTASH_REDIS_REST_URL = "https://prime-buzzard-46382.upstash.io"
LIST_KEY= "notifications"
ACCESS_KEY_ID="08d2c3c50aa0632c38b09d1b22115800"
secretAccessKey="580695da00afd83f184b65a478b1933ba651de23c57f4922aadff80d3f47b215"
endpoint="https://cd7ff564fa8b6a378e331b4edae7a57d.r2.cloudflarestorage.com"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTExNWQ4NTItYWIzZS00ZDIwLWJmN2MtYTcwNDdhNTU4NGZlIiwidGVuYW50X2lkIjoiZTIxODc2ZWZiODI1ODI5MTdhMzY4ZjQ1MDA4YzJkYjZkNjRlNjhlYjhkNGI4ZjExNDMxZmE4YmJlNWE0YWRlYyIsImludGVybmFsX3NlY3JldCI6IjA1MzBlMjUxLTNhYzgtNDc5NC05YTNiLTg4ODY2Y2FkZjg1NiJ9.zmriC-9TuRUZT5IIP4S-kA_H-gMAb59X_HXWJ9PTbME"
JWT_SECRET="123456"
GOOGLE_CLIENT_ID="489371249303-9pfsdn6l52bo46qtgt79kpk18scdohnf.apps.googleusercontent.com"

# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

 [[r2_buckets]]
 binding = "MY_BUCKET"
 bucket_name = "blog"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
