name: Build Succeeds on PR

on:
  pull_request:
    branches: #array of branches
      - master
      - work
        

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #clone repo
      - name: Use NodeJS
        uses: actions/setup-node@v3 #install nodejs
        with:
          node-version: '20' 
      
      - name: Install dependencies
        run: npm install

      - name: Adding DB
        run:  cd apps/backend && npx prisma generate && cd ../..


      - name: Build 
        run: cd apps/frontend && npm run build && cd ../..