name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master
      - work
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSKEY }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: itszafeer/blog-website:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull itszafeer/blog-website:latest  # Replace with your Docker Hub username and repository
