name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        cd apps/frontend
        npm install

    - name: Build 
      run: cd apps/frontend && npm run build && cd ../..

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSKEY }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: itszafeer/blog-website:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull itszafeer/blog-website:latest  # Replace with your Docker Hub username and repository
    
    - name: Deploy Frontend to S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Replace with your AWS region
  
    - name: Sync Frontend to S3
      run: aws s3 sync ./apps/frontend/dist s3://${{ secrets.S3_BUCKET }} --delete
